# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 06:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comuna', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=80)),
                ('cantidad_disponible', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('latitud', models.CharField(max_length=40)),
                ('longitud', models.CharField(max_length=40)),
                ('id_usuario', models.IntegerField()),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arrendados.Ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Propiedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('fecha_nacimiento', models.DateField()),
                ('email', models.CharField(max_length=80, unique=True)),
                ('password', models.CharField(max_length=15)),
                ('telefono', models.IntegerField(null=True)),
                ('direccion', models.CharField(max_length=80, null=True)),
                ('check_offer', models.NullBooleanField(default=False)),
                ('tipo_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arrendados.Tipo_Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario_Califica_Propiedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('calificacion', models.IntegerField()),
                ('comentario', models.CharField(max_length=500, null=True)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arrendados.Propiedad')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arrendados.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario_Califica_Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('calificacion', models.IntegerField()),
                ('usuario1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario1', to='arrendados.Usuario')),
                ('usuario2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario2', to='arrendados.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario_Propiedad',
            fields=[
                ('fecha_inicio', models.DateTimeField(primary_key=True, serialize=False)),
                ('fecha_termino', models.DateTimeField(null=True)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arrendados.Propiedad')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arrendados.Usuario')),
            ],
        ),
        migrations.AddField(
            model_name='propiedad',
            name='tipo_propiedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arrendados.Tipo_Propiedad'),
        ),
        migrations.AddField(
            model_name='foto',
            name='propiedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arrendados.Propiedad'),
        ),
        migrations.AddField(
            model_name='comuna',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arrendados.Region'),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='comuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arrendados.Comuna'),
        ),
    ]
