# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 02:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrendados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('fecha_nacimiento', models.DateField()),
                ('email', models.CharField(max_length=80, unique=True)),
                ('password', models.CharField(max_length=15)),
                ('telefono', models.IntegerField(null=True)),
                ('direccion', models.CharField(max_length=80, null=True)),
                ('check_offer', models.NullBooleanField(default=False)),
                ('tipo_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arrendados.Tipo_Usuario')),
            ],
        ),
    ]
