# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 02:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrendados', '0003_auto_20161225_0242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=80)),
                ('cantidad_disponible', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('latitud', models.CharField(max_length=40)),
                ('longitud', models.CharField(max_length=40)),
            ],
        ),
        migrations.RenameField(
            model_name='ciudad',
            old_name='Comuna_idComuna',
            new_name='comuna',
        ),
        migrations.RenameField(
            model_name='comuna',
            old_name='Region_idRegion',
            new_name='region',
        ),
        migrations.AddField(
            model_name='propiedad',
            name='ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arrendados.Ciudad'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='tipo_propiedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arrendados.Tipo_Propiedad'),
        ),
    ]
